"""initial

Revision ID: 6131d879c68a
Revises: 
Create Date: 2026-05-05 05:59:51.582721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6131d879c68a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breadwinner_name', sa.String(), nullable=True),
    sa.Column('breadwinner_dob', sa.Date(), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('cause_of_death', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('epf_account_number', sa.String(), nullable=True),
    sa.Column('uan_number', sa.String(), nullable=True),
    sa.Column('claimant_name', sa.String(), nullable=True),
    sa.Column('claimant_relationship', sa.String(), nullable=True),
    sa.Column('claimant_aadhaar', sa.String(), nullable=True),
    sa.Column('claimant_bank_account', sa.String(), nullable=True),
    sa.Column('claimant_bank_ifsc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_whatsapp_number'), 'families', ['whatsapp_number'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('onboarding', 'verification_pending', 'audit_failed', 'ready_to_submit', 'filed', name='casestatus'), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('onboarding_data', sa.JSON(), nullable=True),
    sa.Column('entitlement_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('claimed_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='messagedirection'), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'voice', 'document', 'image', 'interactive', name='messagetype'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('agent_handled_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.String(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=False),
    sa.Column('estimated_benefit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('eligible', 'ready', 'filed', 'approved', 'rejected', name='claimstatus'), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('dispute_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('resolution_draft', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    op.drop_table('claims')
    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_table('cases')
    op.drop_index(op.f('ix_families_whatsapp_number'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
