"""add_partners_and_b2b_case_fields

Revision ID: d6d52a1a587e
Revises: 6131d879c68a
Create Date: 2026-05-07 19:22:40.679530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d52a1a587e'
down_revision: Union[str, None] = '6131d879c68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('partner_name')
    )
    op.add_column('cases', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('external_ref_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'cases', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'external_ref_id')
    op.drop_column('cases', 'partner_id')
    op.drop_table('partners')
    # ### end Alembic commands ###
